### ISSUE TITLE
:PlugInstall Doesn't work

### ISSUE THREAD

**Issue by dvchoudh** [physicsKnight/Vim-config#1]
When I do :PlugInstall i get this error. 
![image](https://user-images.githubusercontent.com/68950943/101488099-9692e480-3978-11eb-8171-262cc6d89ae3.png)

**Comment by physicsKnight** [comment]
Did you install vim plug correctly? This is usually the root cause. Make sure you have git installed or else vim plug wont work. Also, it looks like you're missing a 'c' in "call" on the first line

**Comment by dvchoudh** [comment]
i'm afraid to say this but it still doesn't work :(
